spring.application.name=sb-ecom

# 1. Database PostgreSQL
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USER}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.javax.persistence.validation.mode=none

# 3. JWT Configuration

app.jwt.secret=${JWT_SECRET}


app.jwt.expirationMs=86400000
app.jwt.cookie-name=quang_jwt

# 4. Logging
logging.level.org.hibernate.SQL=OFF
logging.level.com.ecommerce.project=DEBUG


spring.servlet.multipart.max-file-size=10MB


spring.servlet.multipart.max-request-size=10MB


project.image=D:/Start/full_stack_ec/sb-ecom/images/

image.base.url=http://localhost:8080/images/

# Stripe key
stripe.secret.key=${STRIPE_SECRET_KEY}





